#!/bin/sh
# /etc/init.d/en-expert-modbus

case "$1" in
  start)
    echo "Starting en-expert modbus service"
    /usr/bin/python3 /opt/en-expert/modbus/main.py &
    ;;
  stop)
    echo "Stopping en-expert modbus service"
    pkill -f /opt/en-expert/modbus/main.py
    ;;
  restart)
    echo "Restarting en-expert modbus service"
    pkill -f /opt/en-expert/modbus/main.py
    /usr/bin/python3 /opt/en-expert/modbus/main.py &
    ;;
  *)
    echo "Usage: /etc/init.d/myservice {start|stop|restart}"
    exit 1
    ;;
esac

exit 0




